AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: true
  # This will disable the rule completely, regardless what other options you put
  # Change the default 80 chars limit value
  # Max: 120
  # If you want the rule only apply to a specific folder/file
  # Include:
  #  - 'app/**/*'
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'spec/*/**'
    - 'Vagrantfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/*/**'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: false
