language: ruby

rvm:
  - 2.7.0

before_install:
  - gem install bundler -v 2.0.2
addons:
  apt:
    update: true
  
after_success:
  - curl http://127.0.0.1:8000

script:
  - rake db:migrate APP_ENV=test
  - rake test
